### PR TITLE
Initialize reversed vector already reversed

### PR DESCRIPTION
**Pull request by realMatthewBenedict**
Probably more efficient to do the initialization reversed rather than initializing it in sorted order and then reversing it

### CODE REVIEW

**Comment by mhahsler** [comment]
Yes, that would be faster, but does not make it much more understandable. A loop would be probably the fastest.

**Comment by realMatthewBenedict** [comment]
Fair enough. What do you think now?

**Comment by mhahsler** [comment]
Lol, yes. But the code will probably produce a warning because NUM_ITEMS is size_t and not int.

**Comment by realMatthewBenedict** [comment]
Oops, sorry about that.

**Comment by realMatthewBenedict** [comment]
To be pedantic though, NUM_ITEMS is initialized with `std::stoi` instead of `std::stoull` or something like that, so it can only ever have the size of an int.

**Comment by mhahsler** [comment]
This is true, but size_t is not on all systems an unsigned long long so it is safer to convert in and then let the compiler promote the int to size_t. Looks like GCC is fine with assigning the size_t to int...

**Pull request merged**
